### ISSUE TITLE
[No discussions sadly] New app!

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/clicky#1]
Thanks. I needed this, as I saw the GNOME screenshot regression in an article. And yes, I hate it. How would you put the button you actually want to click on in the top left corner?

**Comment by clefebvre** [comment]
Sorry @Secret-chest I don't understand your question.

**Comment by Secret-chest** [comment]
> Sorry @Secret-chest I don't understand your question.

Is this scrapped?
