### ISSUE TITLE
Unable to save picture taken

### ISSUE THREAD

**Issue by ghost** [linuxmint/clicky#2]
**Issue**
So far I have installed on Arch to do some tests and follow-ups (helping into adding more of your X-Apps for usage), I understand that this is still a WIP program and some bugs are to be expected, however, I don't see any option that allows saving pictures or checking if the taken pictures are being saved somewhere inside the PC

**Steps to reproduce**
1. Open the app
2. Choose any of the options related to take a screenshot
3. Press the "Take screenshot" button

**Actual behaviour**
Screenshot is taken, however, there is no option of saving the picture

**Expected behaviour**
When the picture is taken, it should allow to save the picture, or have an option that you can choose to save somewhere

**Other information**
This is the option provided
![Captura de pantalla 2022-06-28 142211](https://user-images.githubusercontent.com/1509924/176277975-7ad4282d-660f-4b12-a2f9-b18950e5c7a8.png)

**Comment by clefebvre** [comment]
Hi @SamBurgos it's just a prototype at this stage, only the capture part has been written so far.
