### ISSUE TITLE
Please, allow other file formats

### ISSUE THREAD

**Issue by adrianlopezgalera** [linuxmint/clicky#3]
Hi! I know that Linux Mint is designed to be very simple. I's OK. However, there are small nuances that make it unsuitable/very limiting for advanced users because they force to add extra steps to easy tasks.

For example, the actual screenshot utility doesn't allow to choose any format than ".png". I consider that would be useful if the user could choose easily between the some formats: .jpg (standard, good compression), .webp (screenshots for the web), .png (maximum quality).

Due to that, the user has to open the screenshot with GIMP to change the image format. If these and other details were heard, Linux Mint would become my main system.

Regards.

**Comment by clefebvre** [comment]
Good idea, but we're not there yet in this tool. It's not complete yet.
